#!/bin/bash
# -*- ENCODING: UTF-8 -*-
echo -e "\e[33mEste procedimiento creara un archivo -- .htaccess con el siguiente texto:\e[39m
AuthName \"Directorio privado\"
AuthType Basic
AuthUserFile `pwd -P`/.htpasswd 
require valid-user"
echo -e "\e[33mIngrese usario:\e[39m"
read usuario
echo -e "\e[33mIngrese password:\e[39m"
read pass
#REVISAMOS QUE EL ARCHIVO EXISTA SI: AVISA QUE SE VA A SOBREESCRIBIR / NO:LO ESCRIBE
if [ -f ./.htaccess ];
then
    #AVISAMOS SI REALMETE SE QUIERE SOBREESCRIBIR
    while true; do
        read -r -p "El archivo .htaccess ya existe seguro deseas sobrescribirlo?  Yes or no? " response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
        then
            echo "AuthName \"Directorio privado\"
AuthType Basic
AuthUserFile `pwd -P`/.htpasswd 
require valid-user">.htaccess
                printf "$usuario:$(openssl passwd -crypt $pass)\n" >> .htpasswd
            echo -e "\e[33mTu archivo .htaccess se ha sobreescrito\e[39m"
            exit 0
        else
            echo -e "\e[32mTu archivo .htaccess se mantiene como estaba\e[39m"
            exit 0
        fi
    done
else
    echo -e "\e[323mLos archivos .htaccess y .htpasswd se ha creado con exito\e[39m"
            echo "AuthName \"Directorio privado\"
AuthType Basic
AuthUserFile `pwd -P`/.htpasswd 
require valid-user">.htaccess
printf "$usuario:$(openssl passwd -crypt $pass)\n" >> .htpasswd
fi

exit
